export type GitLabUser = {
  avatarUrl: string | null;
  createdAt: Date;
  email: string | null;
  fullName: string | null;
  gitlabId: number | null;
  glId: number | null;
  glUserAvatarUrl: string | null;
  glUserCreatedAt: Date | null;
  glUserEmail: string | null;
  glUserFullName: string | null;
  glUserId: number | null;
  glUserState: string | null;
  glUserUsername: string | null;
  id: string;
  name: string | null;
  state: string | null;
  updatedAt: Date;
  userEmail: string | null;
  username: string | null;
  userName: string | null;
};
